# CrestronAISkills - Skill Installer
# Auto-generated by the CrestronAISkills web app.
# Placeholders replaced at download time: __SKILL_NAME__, __SKILL_VERSION__, __REGISTRY_URL__, __PAGES_URL__

$skillName    = "__SKILL_NAME__"
$skillVersion = "__SKILL_VERSION__"
$registryUrl  = "__REGISTRY_URL__"
$pagesUrl     = "__PAGES_URL__"

Write-Host "Installing skill: $skillName v$skillVersion" -ForegroundColor Cyan

# 1. Create install directory
$installDir = "$env:USERPROFILE\.copilot\instructions"
if (-not (Test-Path $installDir)) {
    New-Item -ItemType Directory -Force -Path $installDir | Out-Null
    Write-Host "  Created $installDir"
}

# 2. Copy skill.md from the zip (same directory as this script)
$scriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourceMd   = Join-Path $scriptDir "skill.md"
$destMd     = "$installDir\$skillName.md"
Copy-Item $sourceMd $destMd -Force
Write-Host "  Installed skill to $destMd"

# 3. Ensure BurntToast is available for update notifications
if (-not (Get-Module -ListAvailable -Name BurntToast)) {
    Write-Host "  Installing BurntToast module for update notifications..."
    Install-Module BurntToast -Scope CurrentUser -Force
}

# 4. Create the skills config directory and write config file
$skillsDir  = "$env:USERPROFILE\.copilot\skills"
if (-not (Test-Path $skillsDir)) {
    New-Item -ItemType Directory -Force -Path $skillsDir | Out-Null
}

$configPath = "$skillsDir\$skillName-config.json"
$config = [ordered]@{
    name        = $skillName
    version     = $skillVersion
    registryUrl = $registryUrl
    pagesUrl    = $pagesUrl
    installedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.fffZ")
}
$config | ConvertTo-Json | Set-Content $configPath -Encoding UTF8
Write-Host "  Config saved to $configPath"

# 5. Write per-skill update script
$updateScriptPath = "$skillsDir\update-$skillName.ps1"
$updateScriptContent = @'
# Auto-generated update script for __SKILL_NAME__
$config = Get-Content "$env:USERPROFILE\.copilot\skills\__SKILL_NAME__-config.json" | ConvertFrom-Json
$registry = Invoke-RestMethod $config.registryUrl
$latest = ($registry.skills | Where-Object { $_.name -eq $config.name })
if (-not $latest) { exit }
if ($latest.version -ne $config.version) {
    $skillUrl = "$($config.pagesUrl)/skills/$($config.name)/skill.md"
    Invoke-WebRequest $skillUrl -OutFile "$env:USERPROFILE\.copilot\instructions\$($config.name).md"
    $config.version = $latest.version
    $config | ConvertTo-Json | Set-Content "$env:USERPROFILE\.copilot\skills\$($config.name)-config.json"
    Import-Module BurntToast -ErrorAction SilentlyContinue
    New-BurntToastNotification -Text "CrestronAISkills", "Skill '$($config.name)' updated to v$($latest.version)" -ErrorAction SilentlyContinue
    Write-Host "Updated $($config.name) to v$($latest.version)"
} else {
    Write-Host "$($config.name) is already up to date (v$($config.version))"
}
'@
# Replace the placeholder with the actual skill name
$updateScriptContent = $updateScriptContent -replace '__SKILL_NAME__', $skillName
Set-Content $updateScriptPath $updateScriptContent -Encoding UTF8
Write-Host "  Update script saved to $updateScriptPath"

# 6. Register weekly Task Scheduler task
$action   = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-WindowStyle Hidden -File `"$updateScriptPath`""
$trigger  = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Monday -At "9:00AM"
$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Hours 1) -RunOnlyIfNetworkAvailable
Register-ScheduledTask -TaskName "CrestronSkill-$skillName" -Action $action -Trigger $trigger -Settings $settings -RunLevel Limited -Force | Out-Null
Write-Host "  Scheduled task 'CrestronSkill-$skillName' registered (weekly, Monday 9am)"

Write-Host "`n✅ Skill installed! Auto-updates scheduled every Monday at 9am." -ForegroundColor Green
